log:
  level: 0

general:
  allowed-materials:
    - WHEAT
    - STONE
    - LEATHER
  default-sign-type: BIRCH_WALL_SIGN
  default-vault-material: STONE
  sign-text-color: BLACK
  admin-permission: rv.admin



