name: ResourceVaults
version: 2.5
main: com.thepaperraven.ResourceVaults
api-version: 1.18
author: Kilo
description: A plugin that adds vaults for players to store items.
commands:
  rv:
    description: Main command for ResourceVaults.
    usage: /rv <subcommand> [args...]
permissions:
  rv.admin:
    description: Grants access to all ResourceVaults commands.
    default: op

depend:
  - Vault
softdepend:
  - MMOCore
  - MMOItems
  - CMI
  - ProtocolLib
  - MythicMobs
  - PlaceholderAPI